### ISSUE TITLE
[Bug 🐞] Failed to fetch dependencies

### ISSUE THREAD

**Issue by harrytran998** [okikio/bundlejs#36]
Hi @bundlejs, thanks for your great tool. Today I checked my small UI library - wrap of Material UI --> But I have the error like the image below. I hope you can check that!

![image](https://user-images.githubusercontent.com/24296018/181900846-4eb3a914-cffd-4846-b860-7665c9b3efb8.png)

Link: https://bundlejs.com/?q=%40onemind%2Fui

**Comment by okikio** [comment]
@harrytran998 Unfortunately, this doesn't seem to be something I can fix. It seems due to the high number of packages and the even higher number of network requests, browsers are basically giving up. I'll try to optimize the fetch process but I'm not sure I can actually fix this problem.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/17222836/181995606-13ebe45c-984e-417e-9061-917e581b1358.png">

**Comment by okikio** [comment]
After a bit of research I've determined I can't fix this, at least not while bundlejs is running in a browser. I'll look into other alternative solutions to fix this.

**Comment by harrytran998** [comment]
Thanks for your quick response. I think your solution is valid for now(call HTTP in browser). So I will try to pre-bundle MUI. But if you find something interesting alternative solutions, pls let's me know 😆 🙏.

**Comment by okikio** [comment]
@harrytran998 It's now fixed, give it a try https://bundlejs.com/?q=@onemind/ui&bundle

**Comment by okikio** [comment]
Please let me know if you run into this problem again

**Comment by harrytran998** [comment]
Thanks for your work on this 😆  I checked it and everything ok! How do you handle this without call HTTP like before?

**Comment by okikio** [comment]
I made the package fetching algorithm more specific than before, allowing it to avoid fetching packages that could just be ignored or treeshaken away

**Comment by harrytran998** [comment]
thanks for your hard work <3
