### ISSUE TITLE
[Bug] duplicate dependencies if two imports depend on the same package

### ISSUE THREAD

**Issue by yellowsink** [okikio/bundlejs#39]
I was using bundlejs recently to test the bundle sizes of a library I author, crossani.

I was testing the size of it with two addon packages (`@crossani/spring` and `@crossani/flip`), which both import `crossani`.

Bundlejs did not de-duplicate these imports of the same module, causing a bundle size larger than most real-world build tools would produce, in which one copy of the `crossani` package is bundled and used by both.

More generally:
 - import "a";
 - import "b";
 - `a` imports `c`
 - `b` imports `c` too
 - `c` included in bundle twice

**Comment by okikio** [comment]
Hmm...This issue seems to be due to `@crossani/flip` and `@crossani/spring` using 2 different versions of `crossani` 

* https://unpkg.com/browse/@crossani/spring@latest/package.json
* https://unpkg.com/browse/@crossani/flip@latest/package.json

<img width="853" alt="image" src="https://user-images.githubusercontent.com/17222836/199654585-ba6d0c56-8168-4567-9f6f-214be36f59f7.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/17222836/199655022-7caf8aba-2242-46a6-8469-869cae68e933.png">

<img width="421" alt="image" src="https://user-images.githubusercontent.com/17222836/199655111-fbee70d1-4381-4b03-b839-acdd1799561e.png">

**Comment by yellowsink** [comment]
Ah, that makes sense, my fault then - I should be using peer deps come to think of it...

Also strange that they don't have `^` - must be an issue with my monorepo setup or something.

**Comment by yellowsink** [comment]
![image](https://user-images.githubusercontent.com/19270622/199810749-ec1bcae4-ef2e-4f38-a634-8a476a5d8fe8.png)

![image](https://user-images.githubusercontent.com/19270622/199811852-51339d6a-31db-4ca5-9f77-36e40a3f81a7.png)

Was on my end, after fixing package vers is deduping as necessary.

**Comment by okikio** [comment]
TIL, thanks for leaving that feedback
