### ISSUE TITLE
getRequest [Failed at request]

### ISSUE THREAD

**Issue by Shemrock3267** [okikio/bundlejs#48]
Hey, i was trying to check what is wrong with my custom lib (size-wise), without adding webpack to scan it with webpack-bundle-analyzer. I'm using rollup.
But i'm getting get error after i press on 'Build' button.
![failed-request](https://github.com/okikio/bundlejs/assets/10697124/d473a787-2fe6-40f7-ad57-24a57ce92328)

**Comment by okikio** [comment]
The problem is that the `package.json` isn't right. 
<img width="531" alt="image" src="https://github.com/okikio/bundlejs/assets/17222836/702460ae-9599-429a-a15f-923c6736ede6">

<img width="531" alt="image" src="https://github.com/okikio/bundlejs/assets/17222836/f5afd58f-6b65-4b6e-8bc8-1acfce9bb040">

**Comment by Shemrock3267** [comment]
Yeah, my bad. Thanks for pointing it out. Cheers

**Comment by okikio** [comment]
Great to see that it worked out
